In [2]:
import numpy as np #numpy kütüphanesi #!pip install numpy

In [3]:
# matematiksel işlemler için kullanırız

In [10]:
my_list = [10,20,30,40]

In [11]:
type (my_list)

list

In [12]:
np.array(my_list)

array([10, 20, 30, 40])

In [13]:
my_numpy_array = np.array(my_list)

In [14]:
type(my_numpy_array)

numpy.ndarray

In [15]:
my_numpy_array.max()

np.int64(40)

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.random.random(5)

array([0.37046609, 0.4884621 , 0.98990319, 0.07567732, 0.49514328])

In [18]:
#array arithmetic

In [44]:
my_list1 = [2,5]

In [45]:
my_list2 =[2,7]

In [46]:
my_list1 + my_list2

[2, 5, 2, 7]

In [47]:
my_numpy_array1 = np.array(my_list1)

In [48]:
my_numpy_array2 = np.array(my_list2)

In [49]:
my_numpy_array1 + my_numpy_array2

array([ 4, 12])

In [50]:
my_numpy_array1 * my_numpy_array2

array([ 4, 35])

In [51]:
my_numpy_array1 - my_numpy_array2

array([ 0, -2])

In [52]:
my_numpy_array1 / my_numpy_array2

array([1.        , 0.71428571])

In [53]:
my_numpy_array1 * 5

array([10, 25])

In [54]:
my_list1 * 5

[2, 5, 2, 5, 2, 5, 2, 5, 2, 5]

In [55]:
other_array = np.array ([10,20,30,40,50])

In [56]:
other_array.min()

np.int64(10)

In [57]:
other_array.sum()

np.int64(150)

In [58]:
my_numpy_array1

array([2, 5])

In [59]:
other_array

array([10, 20, 30, 40, 50])

In [63]:
# my_numpy_array1 + other_array  HATA VERİR !!

In [64]:
# arange & indexing

In [67]:
np.arange(0,10) #aralık oluştur dizi oluştur

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(0,20,2) # 0'dan 20'ye kadar 2şer 2şer gitsin

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
np_array = np.arange(0,10)

In [71]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np_array[0]

np.int64(0)

In [75]:
np_array [-1] #son elemanı verir

np.int64(9)

In [77]:
np_array [1:4:] #1.indexte başlasın 4.indexte dursun

array([1, 2, 3])

In [79]:
np_array [::-1] #tersten yazdır

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [80]:
#random

In [82]:
np.random.randn(4) #4 tane random sayı

array([ 0.03819412, -1.36258742, -0.16754062,  1.28881275])

In [83]:
np.random.randn(4,4) #matrix verir

array([[-0.0492421 ,  0.77971419,  2.57007953, -0.23059584],
       [ 1.74565818, -0.08801459,  1.3412043 ,  0.50708939],
       [-0.42339199, -0.84032293, -0.28806481, -0.23385738],
       [ 0.67561305,  0.52237183,  0.08451903, -0.93540668]])

In [86]:
np.random.randint(1,300,5) #1-300 arası rastgele 5 tam sayı verir

array([ 18,  52, 212, 297, 126], dtype=int32)

# MATRİX

In [93]:
my_matrix = [[5,10], [15,20]]

In [94]:
my_matrix[0]

[5, 10]

In [95]:
my_matrix[1]

[15, 20]

In [97]:
my_matrix[0][1]

10

In [98]:
# row * column

In [100]:
numpy_matrix = np.array ([[5,10], [15,20]]) #1 listenin içinde 2 iste var

In [101]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [102]:
numpy_matrix[1][0]

np.int64(15)

In [103]:
numpy_matrix.sum()

np.int64(50)

In [104]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [105]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [106]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [107]:
np.random.random((3,2))

array([[0.37361323, 0.53356358],
       [0.61918128, 0.79085592],
       [0.27767922, 0.26165007]])

In [108]:
# matrix arithmetic

In [110]:
first_array = np.array ([[10,20],[30,40]])

In [111]:
second_array = np.array ([[5,15],[25,35]])

In [112]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [113]:
first_array

array([[10, 20],
       [30, 40]])

In [116]:
third_array = np.array ([[50,60]])

In [117]:
third_array

array([[50, 60]])

In [118]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [119]:
fourth_array = np.array([[10,20,30,40,50]])

In [121]:
#first_array + fourth_array

In [122]:
first_array * 2

array([[20, 40],
       [60, 80]])

In [123]:
third_array = np.array ([[10],[20]])

In [124]:
third_array

array([[10],
       [20]])

In [125]:
third_array.shape #2 sıra 1 kolon

(2, 1)

In [128]:
first_array.shape

(2, 2)

In [127]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [129]:
first_array

array([[10, 20],
       [30, 40]])

In [130]:
third_array

array([[10],
       [20]])

# MATRIX MULTIPLICATION

In [132]:
first_array

array([[10, 20],
       [30, 40]])

In [133]:
second_array

array([[ 5, 15],
       [25, 35]])

In [135]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [136]:
# dot product

In [137]:
first_matrix = np.array([[10,20,30]])

In [138]:
first_matrix

array([[10, 20, 30]])

In [139]:
first_matrix.shape

(1, 3)

In [140]:
second_matrix = np.array ([[2,3],[2,3],[2,3]])

In [141]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [142]:
second_matrix.shape

(3, 2)

In [144]:
result_matrix= first_matrix.dot(second_matrix)

In [145]:
result_matrix

array([[120, 180]])

In [147]:
result_matrix.shape

(1, 2)

# NUMPY OPERATIONS

In [150]:
new_array = np.random.randint(1,100,20)

In [151]:
new_array

array([61, 54, 72, 96, 45, 92, 52, 31, 89, 59, 64, 90, 23, 61, 45, 76, 20,
       75, 37, 26], dtype=int32)

In [153]:
new_array > 25 #boolean verir

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True])

In [155]:
new_array[new_array>25] #sadece 25'ten büyükleri göster

array([61, 54, 72, 96, 45, 92, 52, 31, 89, 59, 64, 90, 61, 45, 76, 75, 37,
       26], dtype=int32)

In [156]:
# transpose & reshape

In [158]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [159]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [160]:
matrix_array.shape

(3, 2)

In [162]:
matrix_array.transpose() #row-colonların yerini değiştirir

array([[10, 20, 30],
       [20, 30, 40]])

In [163]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [164]:
random_array = np.random.random ((6,1))

In [165]:
random_array

array([[0.56611849],
       [0.86470306],
       [0.16024605],
       [0.77026602],
       [0.63190529],
       [0.28070558]])

In [166]:
random_array.shape

(6, 1)

In [168]:
random_array.reshape(2,3)

array([[0.56611849, 0.86470306, 0.16024605],
       [0.77026602, 0.63190529, 0.28070558]])

In [169]:
# z-score

In [170]:
data = np.array([10,12,13,15,18,25,100,105])

In [171]:
#outlier

In [172]:
mean = np.mean(data)

In [173]:
mean

np.float64(37.25)

In [174]:
data.sum()/ len(data)

np.float64(37.25)

In [175]:
standart_sapma=np.std(data)

In [176]:
standart_sapma

np.float64(37.9333296719389)

In [178]:
z_scores = (data - mean) / standart_sapma

In [179]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [180]:
# outlier olanların z-score'ı yüksek çıktı
# 1'den büyük olanları gösterelim

In [181]:
z_scores [z_scores>1] # outlier olanları gösterelim

array([1.65421809, 1.78602829])

In [182]:
data[z_scores > 1] # outlier değerleri göster

array([100, 105])

In [183]:
# math equations

In [184]:
# 2x + 3y =8 and 5x + 7y=19

In [185]:
#coefficient : x-y katsayıları

In [186]:
A = np.array ([[2,3],[5,7]]) # coefficient matrix

In [188]:
#constant : sabitleri alalım

In [189]:
b = np.array([8,19])

In [190]:
solutaion = np.linalg.solve (A,b) #lineer cebir(linalg) fonksiyonuna çözümü(solve) verirsek cevabı verir

In [191]:
solutaion

array([1., 2.])